version: '3.8'

services:
  db:
    image: postgres
    container_name: demo-postgres-container
    environment:
      POSTGRES_USER: radhika
      POSTGRES_PASSWORD: radhika
      POSTGRES_DB: pms
    ports:
      - "5433:5432"
    volumes:
      - /Users/radhikamundada/Documents/BajajTraining/Spring/Spring_assessment/data-volume:/var/lib/postgresql/data
  app:
    build: .
    image: demo-v1
    container_name: demo-app-container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pms
      SPRING_DATASOURCE_USERNAME: radhika
      SPRING_DATASOURCE_PASSWORD: radhika
    depends_on:
      - db
